-- Find total customers by countries
SELECT 
			country,
            COUNT(customer_key) AS total_customer
FROM
			customers
GROUP BY 
			country
ORDER BY 
			total_customer DESC ;

-- Find total customers by gender
SELECT 
			gender,
            COUNT(customer_key) AS total_customer
FROM
			customers
GROUP BY 
			gender
ORDER BY 
			total_customer DESC ;
            
-- Find total products by category
SELECT 
			category,
            COUNT(product_key) AS total_products
FROM
			products
GROUP BY 
			category
ORDER BY 
			total_products DESC ;

-- What is the average costs in each category?
SELECT 
			category,
            ROUND(AVG(cost),2) AS avg_cost
FROM
			products
GROUP BY 
			category
ORDER BY 
			avg_cost DESC ;

-- What is the total revenue generated for each category?
SELECT 
			p.category,
            ROUND(SUM(f.sales_amount),2) AS total_revenue
FROM
			fact_sales f
LEFT JOIN
			products p 
            on p.product_key = f.product_key
GROUP BY 
			p.category
ORDER BY 
			total_revenue DESC ;
            
-- Find total revenue is generated by each customer
SELECT 
			c.customer_key,
            c.first_name,
            c.last_name,
            ROUND(SUM(f.sales_amount),2) AS total_revenue
FROM
			fact_sales f
LEFT JOIN
			customers c 
            on c.customer_key = f.customer_key
GROUP BY 
            c.customer_key,
            c.first_name,
            c.last_name
ORDER BY 
			total_revenue DESC;
            
-- What is the distribution of sold items across countries?
SELECT 
			c.country,
            ROUND(SUM(f.quantity),2) AS total_sold_item
FROM
			fact_sales f
LEFT JOIN
			customers c 
            on c.customer_key = f.customer_key
GROUP BY 
            c.country
ORDER BY 
			total_sold_item DESC;